project:
  type: website

website:
  title: "Mapping the Unseen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    background-color: "#F5F5F5"
    banner-color: "white"
    font-family: "Roboto"

editor: visual


